[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/.output/public"

[functions]
  directory = "frontend/.output/server"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/__render"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/__render"
  status = 200

[build.environment]
  NODE_VERSION = "18"